# This creates the PDF report of the whole triage session.

import os
import uuid
from fpdf import FPDF
from datetime import datetime

PDF_FOLDER = "generated_reports"
os.makedirs(PDF_FOLDER, exist_ok=True)

def create_medical_report(username: str, diseases: list, summary: str) -> str:
    """Creates a simple PDF report and returns the file path where it is saved."""
    
    # 1. Setup the PDF document
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # 2. Add the Title
    pdf.set_font("Arial", style="B", size=16)
    pdf.cell(200, 10, txt="Medical Triage Report", ln=True, align='C')
    pdf.ln(10) # Add an empty line

    # 3. Add User Details
    pdf.set_font("Arial", size=12)
    date_today = datetime.now().strftime("%Y-%m-%d")
    pdf.cell(200, 10, txt=f"Patient Name: {username}", ln=True)
    pdf.cell(200, 10, txt=f"Date: {date_today}", ln=True)
    pdf.ln(10)

    # 4. Add the Diseases
    pdf.set_font("Arial", style="B", size=14)
    pdf.cell(200, 10, txt="Possible Diagnoses:", ln=True)
    
    pdf.set_font("Arial", size=12)
    if diseases:
        for disease in diseases:
            pdf.cell(200, 10, txt=f"- {disease}", ln=True)
    else:
        pdf.cell(200, 10, txt="No specific diseases identified.", ln=True)
    
    pdf.ln(10)

    # 5. Add the Summary
    pdf.set_font("Arial", style="B", size=14)
    pdf.cell(200, 10, txt="Consultation Summary:", ln=True)
    
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 10, txt=summary)
    pdf.ln(15)

    # 6. Add the AI Safety Disclaimer
    pdf.set_text_color(128, 128, 128)
    pdf.set_font("Arial", style="I", size=10)
    disclaimer_text = (
        "Disclaimer: This report was generated by an Artificial Intelligence system "
        "and is for informational purposes only. It is not a substitute for professional "
        "medical advice, diagnosis, or treatment. Always consult a qualified healthcare "
        "provider or doctor for medical decisions."
    )
    pdf.multi_cell(0, 6, txt=disclaimer_text)

    # 7. Save the file with a unique ID
    unique_filename = f"report_{uuid.uuid4().hex[:8]}.pdf"
    file_path = os.path.join(PDF_FOLDER, unique_filename)
    
    pdf.output(file_path)
    
    return file_path